Testing gh env
awslabs/aws-iot-device-client pull request #350
Opened 2022-10-25 18:31 UTC by RogerZhongAWS

### Motivation
- Please give a brief description for the background of this change.
- Issue number: 

### Modifications
#### Change summary
Please describe what changes are included in this pull request. 

#### Revision diff summary
If there is more than one revision, please explain what has been changed since the last revision.

### Testing
 **Is your change tested? If not, please justify the reason.**  
 **Please list your testing steps and test results.** 
- CI test run result: <link>

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-08 20:56 UTC, shangabl commented
LGTM but where do you have a test run from a fork? Maybe merging this from a fork would actually be the best way to prove its working for forks? Wanna make sure the fork CI runs from fork and isn't duplicated.

2022-11-08 22:32 UTC, RogerZhongAWS commented
> LGTM but where do you have a test run from a fork? Maybe merging this from a fork would actually be the best way to prove its working for forks? Wanna make sure the fork CI runs from fork and isn't duplicated.

#352
#354

2022-11-08 22:39 UTC, shangabl submitted a review, later dismissed

2022-11-09 17:20 UTC, shangabl commented
Oh I forgot can you update the contributing guidelines?

2022-12-03 01:17 UTC, marcoemorais-aws requested changes

2022-12-03 01:17 UTC, marcoemorais-aws commented on .github/workflows/cppcheck.yml
> +        with:
This is less secure, pls remove.

2022-12-03 01:17 UTC, marcoemorais-aws commented on .github/workflows/lint.yml
> +        with:
This is less secure, pls remove.

2022-12-03 01:17 UTC, marcoemorais-aws commented on .github/workflows/lint.yml
> +          git branch
Prolly leftover from your debugging.

2022-12-06 23:55 UTC, marcoemorais-aws approved these changes

2022-12-06 23:56 UTC, shangabl submitted a review, later dismissed

2022-12-07 19:35 UTC, shangabl approved these changes

2022-12-07 19:54 UTC, HarshGandhi-AWS approved these changes

2022-12-07 19:55 UTC, merged